spring:
 data:
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
logging:
  level:
    org.springframework.security.web: DEBUG  # 웹 시큐리티 관련 디버그
    org.springframework.security.oauth2: INFO  # OAuth2 관련 로그는 INFO로 제한
    root: INFO  # 전체적인 루트 로그는 INFO로 줄여서 기본적인 정보만 기록
    org:
      hibernate:
        SQL: WARN  # SQL 쿼리 로그는 WARN으로 줄여서 문제 발생 시만 기록
        type:
          descriptor:
            sql:
              BasicBinder: ERROR  # SQL 바인딩 관련 문제는 ERROR로 한정, 필요할 때만 WARN으로 조정